import React from 'react'
import RepoItem from './RepoItem'

const repos = [
    {
        "id": 10270250,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==",
        "name": "react",
        "full_name": "facebook/react",
        "private": false,
        "owner": {
            "login": "facebook",
            "id": 69631,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5NjMx",
            "avatar_url": "https://avatars.githubusercontent.com/u/69631?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/facebook",
            "html_url": "https://github.com/facebook",
            "followers_url": "https://api.github.com/users/facebook/followers",
            "following_url": "https://api.github.com/users/facebook/following{/other_user}",
            "gists_url": "https://api.github.com/users/facebook/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/facebook/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/facebook/subscriptions",
            "organizations_url": "https://api.github.com/users/facebook/orgs",
            "repos_url": "https://api.github.com/users/facebook/repos",
            "events_url": "https://api.github.com/users/facebook/events{/privacy}",
            "received_events_url": "https://api.github.com/users/facebook/received_events",
            "type": "Organization",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/facebook/react",
        "description": "The library for web and native user interfaces.",
        "fork": false,
        "url": "https://api.github.com/repos/facebook/react",
        "forks_url": "https://api.github.com/repos/facebook/react/forks",
        "keys_url": "https://api.github.com/repos/facebook/react/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/facebook/react/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/facebook/react/teams",
        "hooks_url": "https://api.github.com/repos/facebook/react/hooks",
        "issue_events_url": "https://api.github.com/repos/facebook/react/issues/events{/number}",
        "events_url": "https://api.github.com/repos/facebook/react/events",
        "assignees_url": "https://api.github.com/repos/facebook/react/assignees{/user}",
        "branches_url": "https://api.github.com/repos/facebook/react/branches{/branch}",
        "tags_url": "https://api.github.com/repos/facebook/react/tags",
        "blobs_url": "https://api.github.com/repos/facebook/react/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/facebook/react/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/facebook/react/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/facebook/react/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/facebook/react/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/facebook/react/languages",
        "stargazers_url": "https://api.github.com/repos/facebook/react/stargazers",
        "contributors_url": "https://api.github.com/repos/facebook/react/contributors",
        "subscribers_url": "https://api.github.com/repos/facebook/react/subscribers",
        "subscription_url": "https://api.github.com/repos/facebook/react/subscription",
        "commits_url": "https://api.github.com/repos/facebook/react/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/facebook/react/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/facebook/react/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/facebook/react/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/facebook/react/contents/{+path}",
        "compare_url": "https://api.github.com/repos/facebook/react/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/facebook/react/merges",
        "archive_url": "https://api.github.com/repos/facebook/react/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/facebook/react/downloads",
        "issues_url": "https://api.github.com/repos/facebook/react/issues{/number}",
        "pulls_url": "https://api.github.com/repos/facebook/react/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/facebook/react/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/facebook/react/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/facebook/react/labels{/name}",
        "releases_url": "https://api.github.com/repos/facebook/react/releases{/id}",
        "deployments_url": "https://api.github.com/repos/facebook/react/deployments",
        "created_at": "2013-05-24T16:15:54Z",
        "updated_at": "2025-07-18T19:17:24Z",
        "pushed_at": "2025-07-18T12:58:25Z",
        "git_url": "git://github.com/facebook/react.git",
        "ssh_url": "git@github.com:facebook/react.git",
        "clone_url": "https://github.com/facebook/react.git",
        "svn_url": "https://github.com/facebook/react",
        "homepage": "https://react.dev",
        "size": 1050254,
        "stargazers_count": 237388,
        "watchers_count": 237388,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": true,
        "forks_count": 48955,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1165,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "declarative",
            "frontend",
            "javascript",
            "library",
            "react",
            "ui"
        ],
        "visibility": "public",
        "forks": 48955,
        "open_issues": 1165,
        "watchers": 237388,
        "default_branch": "main",
        "score": 1.0
    },
    {
        "id": 126577260,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMjY1NzcyNjA=",
        "name": "javascript-algorithms",
        "full_name": "trekhleb/javascript-algorithms",
        "private": false,
        "owner": {
            "login": "trekhleb",
            "id": 3000285,
            "node_id": "MDQ6VXNlcjMwMDAyODU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/3000285?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/trekhleb",
            "html_url": "https://github.com/trekhleb",
            "followers_url": "https://api.github.com/users/trekhleb/followers",
            "following_url": "https://api.github.com/users/trekhleb/following{/other_user}",
            "gists_url": "https://api.github.com/users/trekhleb/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/trekhleb/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/trekhleb/subscriptions",
            "organizations_url": "https://api.github.com/users/trekhleb/orgs",
            "repos_url": "https://api.github.com/users/trekhleb/repos",
            "events_url": "https://api.github.com/users/trekhleb/events{/privacy}",
            "received_events_url": "https://api.github.com/users/trekhleb/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/trekhleb/javascript-algorithms",
        "description": "📝 Algorithms and data structures implemented in JavaScript with explanations and links to further readings",
        "fork": false,
        "url": "https://api.github.com/repos/trekhleb/javascript-algorithms",
        "forks_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/forks",
        "keys_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/teams",
        "hooks_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/hooks",
        "issue_events_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/issues/events{/number}",
        "events_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/events",
        "assignees_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/assignees{/user}",
        "branches_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/branches{/branch}",
        "tags_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/tags",
        "blobs_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/languages",
        "stargazers_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/stargazers",
        "contributors_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/contributors",
        "subscribers_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/subscribers",
        "subscription_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/subscription",
        "commits_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/contents/{+path}",
        "compare_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/merges",
        "archive_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/downloads",
        "issues_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/issues{/number}",
        "pulls_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/labels{/name}",
        "releases_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/releases{/id}",
        "deployments_url": "https://api.github.com/repos/trekhleb/javascript-algorithms/deployments",
        "created_at": "2018-03-24T07:47:04Z",
        "updated_at": "2025-07-18T17:04:28Z",
        "pushed_at": "2025-02-12T16:19:59Z",
        "git_url": "git://github.com/trekhleb/javascript-algorithms.git",
        "ssh_url": "git@github.com:trekhleb/javascript-algorithms.git",
        "clone_url": "https://github.com/trekhleb/javascript-algorithms.git",
        "svn_url": "https://github.com/trekhleb/javascript-algorithms",
        "homepage": "",
        "size": 13564,
        "stargazers_count": 192205,
        "watchers_count": 192205,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 30754,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 364,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "algorithm",
            "algorithms",
            "computer-science",
            "data-structures",
            "interview",
            "interview-preparation",
            "javascript",
            "javascript-algorithms"
        ],
        "visibility": "public",
        "forks": 30754,
        "open_issues": 364,
        "watchers": 192205,
        "default_branch": "master",
        "score": 1.0
    },
    {
        "id": 6498492,
        "node_id": "MDEwOlJlcG9zaXRvcnk2NDk4NDky",
        "name": "javascript",
        "full_name": "airbnb/javascript",
        "private": false,
        "owner": {
            "login": "airbnb",
            "id": 698437,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjY5ODQzNw==",
            "avatar_url": "https://avatars.githubusercontent.com/u/698437?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/airbnb",
            "html_url": "https://github.com/airbnb",
            "followers_url": "https://api.github.com/users/airbnb/followers",
            "following_url": "https://api.github.com/users/airbnb/following{/other_user}",
            "gists_url": "https://api.github.com/users/airbnb/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/airbnb/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/airbnb/subscriptions",
            "organizations_url": "https://api.github.com/users/airbnb/orgs",
            "repos_url": "https://api.github.com/users/airbnb/repos",
            "events_url": "https://api.github.com/users/airbnb/events{/privacy}",
            "received_events_url": "https://api.github.com/users/airbnb/received_events",
            "type": "Organization",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/airbnb/javascript",
        "description": "JavaScript Style Guide",
        "fork": false,
        "url": "https://api.github.com/repos/airbnb/javascript",
        "forks_url": "https://api.github.com/repos/airbnb/javascript/forks",
        "keys_url": "https://api.github.com/repos/airbnb/javascript/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/airbnb/javascript/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/airbnb/javascript/teams",
        "hooks_url": "https://api.github.com/repos/airbnb/javascript/hooks",
        "issue_events_url": "https://api.github.com/repos/airbnb/javascript/issues/events{/number}",
        "events_url": "https://api.github.com/repos/airbnb/javascript/events",
        "assignees_url": "https://api.github.com/repos/airbnb/javascript/assignees{/user}",
        "branches_url": "https://api.github.com/repos/airbnb/javascript/branches{/branch}",
        "tags_url": "https://api.github.com/repos/airbnb/javascript/tags",
        "blobs_url": "https://api.github.com/repos/airbnb/javascript/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/airbnb/javascript/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/airbnb/javascript/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/airbnb/javascript/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/airbnb/javascript/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/airbnb/javascript/languages",
        "stargazers_url": "https://api.github.com/repos/airbnb/javascript/stargazers",
        "contributors_url": "https://api.github.com/repos/airbnb/javascript/contributors",
        "subscribers_url": "https://api.github.com/repos/airbnb/javascript/subscribers",
        "subscription_url": "https://api.github.com/repos/airbnb/javascript/subscription",
        "commits_url": "https://api.github.com/repos/airbnb/javascript/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/airbnb/javascript/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/airbnb/javascript/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/airbnb/javascript/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/airbnb/javascript/contents/{+path}",
        "compare_url": "https://api.github.com/repos/airbnb/javascript/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/airbnb/javascript/merges",
        "archive_url": "https://api.github.com/repos/airbnb/javascript/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/airbnb/javascript/downloads",
        "issues_url": "https://api.github.com/repos/airbnb/javascript/issues{/number}",
        "pulls_url": "https://api.github.com/repos/airbnb/javascript/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/airbnb/javascript/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/airbnb/javascript/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/airbnb/javascript/labels{/name}",
        "releases_url": "https://api.github.com/repos/airbnb/javascript/releases{/id}",
        "deployments_url": "https://api.github.com/repos/airbnb/javascript/deployments",
        "created_at": "2012-11-01T23:13:50Z",
        "updated_at": "2025-07-18T18:25:26Z",
        "pushed_at": "2024-12-09T06:56:18Z",
        "git_url": "git://github.com/airbnb/javascript.git",
        "ssh_url": "git@github.com:airbnb/javascript.git",
        "clone_url": "https://github.com/airbnb/javascript.git",
        "svn_url": "https://github.com/airbnb/javascript",
        "homepage": null,
        "size": 3689,
        "stargazers_count": 147082,
        "watchers_count": 147082,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 26779,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 171,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "arrow-functions",
            "es2015",
            "es2016",
            "es2017",
            "es2018",
            "es6",
            "eslint",
            "javascript",
            "linting",
            "naming-conventions",
            "style-guide",
            "style-linter",
            "styleguide",
            "tc39"
        ],
        "visibility": "public",
        "forks": 26779,
        "open_issues": 171,
        "watchers": 147082,
        "default_branch": "master",
        "score": 1.0
    },
    {
        "id": 70107786,
        "node_id": "MDEwOlJlcG9zaXRvcnk3MDEwNzc4Ng==",
        "name": "next.js",
        "full_name": "vercel/next.js",
        "private": false,
        "owner": {
            "login": "vercel",
            "id": 14985020,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjE0OTg1MDIw",
            "avatar_url": "https://avatars.githubusercontent.com/u/14985020?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/vercel",
            "html_url": "https://github.com/vercel",
            "followers_url": "https://api.github.com/users/vercel/followers",
            "following_url": "https://api.github.com/users/vercel/following{/other_user}",
            "gists_url": "https://api.github.com/users/vercel/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/vercel/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/vercel/subscriptions",
            "organizations_url": "https://api.github.com/users/vercel/orgs",
            "repos_url": "https://api.github.com/users/vercel/repos",
            "events_url": "https://api.github.com/users/vercel/events{/privacy}",
            "received_events_url": "https://api.github.com/users/vercel/received_events",
            "type": "Organization",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/vercel/next.js",
        "description": "The React Framework",
        "fork": false,
        "url": "https://api.github.com/repos/vercel/next.js",
        "forks_url": "https://api.github.com/repos/vercel/next.js/forks",
        "keys_url": "https://api.github.com/repos/vercel/next.js/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/vercel/next.js/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/vercel/next.js/teams",
        "hooks_url": "https://api.github.com/repos/vercel/next.js/hooks",
        "issue_events_url": "https://api.github.com/repos/vercel/next.js/issues/events{/number}",
        "events_url": "https://api.github.com/repos/vercel/next.js/events",
        "assignees_url": "https://api.github.com/repos/vercel/next.js/assignees{/user}",
        "branches_url": "https://api.github.com/repos/vercel/next.js/branches{/branch}",
        "tags_url": "https://api.github.com/repos/vercel/next.js/tags",
        "blobs_url": "https://api.github.com/repos/vercel/next.js/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/vercel/next.js/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/vercel/next.js/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/vercel/next.js/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/vercel/next.js/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/vercel/next.js/languages",
        "stargazers_url": "https://api.github.com/repos/vercel/next.js/stargazers",
        "contributors_url": "https://api.github.com/repos/vercel/next.js/contributors",
        "subscribers_url": "https://api.github.com/repos/vercel/next.js/subscribers",
        "subscription_url": "https://api.github.com/repos/vercel/next.js/subscription",
        "commits_url": "https://api.github.com/repos/vercel/next.js/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/vercel/next.js/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/vercel/next.js/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/vercel/next.js/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/vercel/next.js/contents/{+path}",
        "compare_url": "https://api.github.com/repos/vercel/next.js/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/vercel/next.js/merges",
        "archive_url": "https://api.github.com/repos/vercel/next.js/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/vercel/next.js/downloads",
        "issues_url": "https://api.github.com/repos/vercel/next.js/issues{/number}",
        "pulls_url": "https://api.github.com/repos/vercel/next.js/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/vercel/next.js/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/vercel/next.js/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/vercel/next.js/labels{/name}",
        "releases_url": "https://api.github.com/repos/vercel/next.js/releases{/id}",
        "deployments_url": "https://api.github.com/repos/vercel/next.js/deployments",
        "created_at": "2016-10-05T23:32:51Z",
        "updated_at": "2025-07-18T19:31:39Z",
        "pushed_at": "2025-07-18T19:17:51Z",
        "git_url": "git://github.com/vercel/next.js.git",
        "ssh_url": "git@github.com:vercel/next.js.git",
        "clone_url": "https://github.com/vercel/next.js.git",
        "svn_url": "https://github.com/vercel/next.js",
        "homepage": "https://nextjs.org",
        "size": 2294805,
        "stargazers_count": 133278,
        "watchers_count": 133278,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": true,
        "forks_count": 28868,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 3261,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "blog",
            "browser",
            "compiler",
            "components",
            "hybrid",
            "nextjs",
            "node",
            "react",
            "server-rendering",
            "ssg",
            "static",
            "static-site-generator",
            "universal",
            "vercel"
        ],
        "visibility": "public",
        "forks": 28868,
        "open_issues": 3261,
        "watchers": 133278,
        "default_branch": "canary",
        "score": 1.0
    },
    {
        "id": 574523116,
        "node_id": "R_kgDOIj6G7A",
        "name": "awesome-chatgpt-prompts",
        "full_name": "f/awesome-chatgpt-prompts",
        "private": false,
        "owner": {
            "login": "f",
            "id": 196477,
            "node_id": "MDQ6VXNlcjE5NjQ3Nw==",
            "avatar_url": "https://avatars.githubusercontent.com/u/196477?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/f",
            "html_url": "https://github.com/f",
            "followers_url": "https://api.github.com/users/f/followers",
            "following_url": "https://api.github.com/users/f/following{/other_user}",
            "gists_url": "https://api.github.com/users/f/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/f/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/f/subscriptions",
            "organizations_url": "https://api.github.com/users/f/orgs",
            "repos_url": "https://api.github.com/users/f/repos",
            "events_url": "https://api.github.com/users/f/events{/privacy}",
            "received_events_url": "https://api.github.com/users/f/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/f/awesome-chatgpt-prompts",
        "description": "This repo includes ChatGPT prompt curation to use ChatGPT and other LLM tools better.",
        "fork": false,
        "url": "https://api.github.com/repos/f/awesome-chatgpt-prompts",
        "forks_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/forks",
        "keys_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/teams",
        "hooks_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/hooks",
        "issue_events_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/issues/events{/number}",
        "events_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/events",
        "assignees_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/assignees{/user}",
        "branches_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/branches{/branch}",
        "tags_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/tags",
        "blobs_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/languages",
        "stargazers_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/stargazers",
        "contributors_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/contributors",
        "subscribers_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/subscribers",
        "subscription_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/subscription",
        "commits_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/contents/{+path}",
        "compare_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/merges",
        "archive_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/downloads",
        "issues_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/issues{/number}",
        "pulls_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/labels{/name}",
        "releases_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/releases{/id}",
        "deployments_url": "https://api.github.com/repos/f/awesome-chatgpt-prompts/deployments",
        "created_at": "2022-12-05T13:54:13Z",
        "updated_at": "2025-07-18T19:31:52Z",
        "pushed_at": "2025-07-10T18:23:02Z",
        "git_url": "git://github.com/f/awesome-chatgpt-prompts.git",
        "ssh_url": "git@github.com:f/awesome-chatgpt-prompts.git",
        "clone_url": "https://github.com/f/awesome-chatgpt-prompts.git",
        "svn_url": "https://github.com/f/awesome-chatgpt-prompts",
        "homepage": "https://prompts.chat",
        "size": 1509,
        "stargazers_count": 130814,
        "watchers_count": 130814,
        "language": "JavaScript",
        "has_issues": false,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 17349,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 277,
        "license": {
            "key": "cc0-1.0",
            "name": "Creative Commons Zero v1.0 Universal",
            "spdx_id": "CC0-1.0",
            "url": "https://api.github.com/licenses/cc0-1.0",
            "node_id": "MDc6TGljZW5zZTY="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "bots",
            "chatbot",
            "chatgpt",
            "chatgpt-api",
            "language"
        ],
        "visibility": "public",
        "forks": 17349,
        "open_issues": 277,
        "watchers": 130814,
        "default_branch": "main",
        "score": 1.0
    },
    {
        "id": 112507086,
        "node_id": "MDEwOlJlcG9zaXRvcnkxMTI1MDcwODY=",
        "name": "30-seconds-of-code",
        "full_name": "Chalarangelo/30-seconds-of-code",
        "private": false,
        "owner": {
            "login": "Chalarangelo",
            "id": 8281875,
            "node_id": "MDQ6VXNlcjgyODE4NzU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8281875?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Chalarangelo",
            "html_url": "https://github.com/Chalarangelo",
            "followers_url": "https://api.github.com/users/Chalarangelo/followers",
            "following_url": "https://api.github.com/users/Chalarangelo/following{/other_user}",
            "gists_url": "https://api.github.com/users/Chalarangelo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Chalarangelo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Chalarangelo/subscriptions",
            "organizations_url": "https://api.github.com/users/Chalarangelo/orgs",
            "repos_url": "https://api.github.com/users/Chalarangelo/repos",
            "events_url": "https://api.github.com/users/Chalarangelo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Chalarangelo/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/Chalarangelo/30-seconds-of-code",
        "description": "Coding articles to level up your development skills",
        "fork": false,
        "url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code",
        "forks_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/forks",
        "keys_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/teams",
        "hooks_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/hooks",
        "issue_events_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/events",
        "assignees_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/tags",
        "blobs_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/languages",
        "stargazers_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/stargazers",
        "contributors_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/contributors",
        "subscribers_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/subscribers",
        "subscription_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/subscription",
        "commits_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/merges",
        "archive_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/downloads",
        "issues_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/labels{/name}",
        "releases_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Chalarangelo/30-seconds-of-code/deployments",
        "created_at": "2017-11-29T17:35:03Z",
        "updated_at": "2025-07-18T19:20:16Z",
        "pushed_at": "2025-07-13T13:19:49Z",
        "git_url": "git://github.com/Chalarangelo/30-seconds-of-code.git",
        "ssh_url": "git@github.com:Chalarangelo/30-seconds-of-code.git",
        "clone_url": "https://github.com/Chalarangelo/30-seconds-of-code.git",
        "svn_url": "https://github.com/Chalarangelo/30-seconds-of-code",
        "homepage": "https://30secondsofcode.org/",
        "size": 740268,
        "stargazers_count": 124611,
        "watchers_count": 124611,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 12254,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 1,
        "license": {
            "key": "cc-by-4.0",
            "name": "Creative Commons Attribution 4.0 International",
            "spdx_id": "CC-BY-4.0",
            "url": "https://api.github.com/licenses/cc-by-4.0",
            "node_id": "MDc6TGljZW5zZTI1"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": true,
        "topics": [
            "astro",
            "awesome-list",
            "css",
            "education",
            "es6-javascript",
            "git",
            "html",
            "javascript",
            "learn-to-code",
            "learning-resources",
            "nodejs",
            "programming",
            "snippets"
        ],
        "visibility": "public",
        "forks": 12254,
        "open_issues": 1,
        "watchers": 124611,
        "default_branch": "master",
        "score": 1.0
    },
    {
        "id": 27193779,
        "node_id": "MDEwOlJlcG9zaXRvcnkyNzE5Mzc3OQ==",
        "name": "node",
        "full_name": "nodejs/node",
        "private": false,
        "owner": {
            "login": "nodejs",
            "id": 9950313,
            "node_id": "MDEyOk9yZ2FuaXphdGlvbjk5NTAzMTM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/9950313?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/nodejs",
            "html_url": "https://github.com/nodejs",
            "followers_url": "https://api.github.com/users/nodejs/followers",
            "following_url": "https://api.github.com/users/nodejs/following{/other_user}",
            "gists_url": "https://api.github.com/users/nodejs/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/nodejs/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/nodejs/subscriptions",
            "organizations_url": "https://api.github.com/users/nodejs/orgs",
            "repos_url": "https://api.github.com/users/nodejs/repos",
            "events_url": "https://api.github.com/users/nodejs/events{/privacy}",
            "received_events_url": "https://api.github.com/users/nodejs/received_events",
            "type": "Organization",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/nodejs/node",
        "description": "Node.js JavaScript runtime ✨🐢🚀✨",
        "fork": false,
        "url": "https://api.github.com/repos/nodejs/node",
        "forks_url": "https://api.github.com/repos/nodejs/node/forks",
        "keys_url": "https://api.github.com/repos/nodejs/node/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/nodejs/node/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/nodejs/node/teams",
        "hooks_url": "https://api.github.com/repos/nodejs/node/hooks",
        "issue_events_url": "https://api.github.com/repos/nodejs/node/issues/events{/number}",
        "events_url": "https://api.github.com/repos/nodejs/node/events",
        "assignees_url": "https://api.github.com/repos/nodejs/node/assignees{/user}",
        "branches_url": "https://api.github.com/repos/nodejs/node/branches{/branch}",
        "tags_url": "https://api.github.com/repos/nodejs/node/tags",
        "blobs_url": "https://api.github.com/repos/nodejs/node/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/nodejs/node/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/nodejs/node/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/nodejs/node/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/nodejs/node/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/nodejs/node/languages",
        "stargazers_url": "https://api.github.com/repos/nodejs/node/stargazers",
        "contributors_url": "https://api.github.com/repos/nodejs/node/contributors",
        "subscribers_url": "https://api.github.com/repos/nodejs/node/subscribers",
        "subscription_url": "https://api.github.com/repos/nodejs/node/subscription",
        "commits_url": "https://api.github.com/repos/nodejs/node/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/nodejs/node/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/nodejs/node/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/nodejs/node/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/nodejs/node/contents/{+path}",
        "compare_url": "https://api.github.com/repos/nodejs/node/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/nodejs/node/merges",
        "archive_url": "https://api.github.com/repos/nodejs/node/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/nodejs/node/downloads",
        "issues_url": "https://api.github.com/repos/nodejs/node/issues{/number}",
        "pulls_url": "https://api.github.com/repos/nodejs/node/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/nodejs/node/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/nodejs/node/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/nodejs/node/labels{/name}",
        "releases_url": "https://api.github.com/repos/nodejs/node/releases{/id}",
        "deployments_url": "https://api.github.com/repos/nodejs/node/deployments",
        "created_at": "2014-11-26T19:57:11Z",
        "updated_at": "2025-07-18T19:32:07Z",
        "pushed_at": "2025-07-18T15:24:42Z",
        "git_url": "git://github.com/nodejs/node.git",
        "ssh_url": "git@github.com:nodejs/node.git",
        "clone_url": "https://github.com/nodejs/node.git",
        "svn_url": "https://github.com/nodejs/node",
        "homepage": "https://nodejs.org",
        "size": 1313595,
        "stargazers_count": 112261,
        "watchers_count": 112261,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 32184,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 2303,
        "license": {
            "key": "other",
            "name": "Other",
            "spdx_id": "NOASSERTION",
            "url": null,
            "node_id": "MDc6TGljZW5zZTA="
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "javascript",
            "js",
            "linux",
            "macos",
            "mit",
            "node",
            "nodejs",
            "runtime",
            "windows"
        ],
        "visibility": "public",
        "forks": 32184,
        "open_issues": 2303,
        "watchers": 112261,
        "default_branch": "main",
        "score": 1.0
    },
    {
        "id": 576201,
        "node_id": "MDEwOlJlcG9zaXRvcnk1NzYyMDE=",
        "name": "three.js",
        "full_name": "mrdoob/three.js",
        "private": false,
        "owner": {
            "login": "mrdoob",
            "id": 97088,
            "node_id": "MDQ6VXNlcjk3MDg4",
            "avatar_url": "https://avatars.githubusercontent.com/u/97088?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mrdoob",
            "html_url": "https://github.com/mrdoob",
            "followers_url": "https://api.github.com/users/mrdoob/followers",
            "following_url": "https://api.github.com/users/mrdoob/following{/other_user}",
            "gists_url": "https://api.github.com/users/mrdoob/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mrdoob/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mrdoob/subscriptions",
            "organizations_url": "https://api.github.com/users/mrdoob/orgs",
            "repos_url": "https://api.github.com/users/mrdoob/repos",
            "events_url": "https://api.github.com/users/mrdoob/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mrdoob/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": false
        },
        "html_url": "https://github.com/mrdoob/three.js",
        "description": "JavaScript 3D Library.",
        "fork": false,
        "url": "https://api.github.com/repos/mrdoob/three.js",
        "forks_url": "https://api.github.com/repos/mrdoob/three.js/forks",
        "keys_url": "https://api.github.com/repos/mrdoob/three.js/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/mrdoob/three.js/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/mrdoob/three.js/teams",
        "hooks_url": "https://api.github.com/repos/mrdoob/three.js/hooks",
        "issue_events_url": "https://api.github.com/repos/mrdoob/three.js/issues/events{/number}",
        "events_url": "https://api.github.com/repos/mrdoob/three.js/events",
        "assignees_url": "https://api.github.com/repos/mrdoob/three.js/assignees{/user}",
        "branches_url": "https://api.github.com/repos/mrdoob/three.js/branches{/branch}",
        "tags_url": "https://api.github.com/repos/mrdoob/three.js/tags",
        "blobs_url": "https://api.github.com/repos/mrdoob/three.js/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/mrdoob/three.js/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/mrdoob/three.js/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/mrdoob/three.js/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/mrdoob/three.js/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/mrdoob/three.js/languages",
        "stargazers_url": "https://api.github.com/repos/mrdoob/three.js/stargazers",
        "contributors_url": "https://api.github.com/repos/mrdoob/three.js/contributors",
        "subscribers_url": "https://api.github.com/repos/mrdoob/three.js/subscribers",
        "subscription_url": "https://api.github.com/repos/mrdoob/three.js/subscription",
        "commits_url": "https://api.github.com/repos/mrdoob/three.js/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/mrdoob/three.js/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/mrdoob/three.js/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/mrdoob/three.js/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/mrdoob/three.js/contents/{+path}",
        "compare_url": "https://api.github.com/repos/mrdoob/three.js/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/mrdoob/three.js/merges",
        "archive_url": "https://api.github.com/repos/mrdoob/three.js/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/mrdoob/three.js/downloads",
        "issues_url": "https://api.github.com/repos/mrdoob/three.js/issues{/number}",
        "pulls_url": "https://api.github.com/repos/mrdoob/three.js/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/mrdoob/three.js/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/mrdoob/three.js/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/mrdoob/three.js/labels{/name}",
        "releases_url": "https://api.github.com/repos/mrdoob/three.js/releases{/id}",
        "deployments_url": "https://api.github.com/repos/mrdoob/three.js/deployments",
        "created_at": "2010-03-23T18:58:01Z",
        "updated_at": "2025-07-18T18:26:15Z",
        "pushed_at": "2025-07-18T17:05:49Z",
        "git_url": "git://github.com/mrdoob/three.js.git",
        "ssh_url": "git@github.com:mrdoob/three.js.git",
        "clone_url": "https://github.com/mrdoob/three.js.git",
        "svn_url": "https://github.com/mrdoob/three.js",
        "homepage": "https://threejs.org/",
        "size": 1448597,
        "stargazers_count": 107681,
        "watchers_count": 107681,
        "language": "JavaScript",
        "has_issues": true,
        "has_projects": false,
        "has_downloads": false,
        "has_wiki": true,
        "has_pages": true,
        "has_discussions": false,
        "forks_count": 35897,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 569,
        "license": {
            "key": "mit",
            "name": "MIT License",
            "spdx_id": "MIT",
            "url": "https://api.github.com/licenses/mit",
            "node_id": "MDc6TGljZW5zZTEz"
        },
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [
            "3d",
            "augmented-reality",
            "canvas",
            "html5",
            "javascript",
            "svg",
            "virtual-reality",
            "webaudio",
            "webgl",
            "webgl2",
            "webgpu",
            "webxr"
        ],
        "visibility": "public",
        "forks": 35897,
        "open_issues": 569,
        "watchers": 107681,
        "default_branch": "dev",
        "score": 1.0
    },
]

export default function SearchResults() {
    return (
        <div className='flex flex-col gap-y-3 w-full '>
            <span className='w-full'>
                <p className='text-xs text-gray-500'>
                    Total Results {repos.length}
                </p>
            </span>

            <ul className='divide-y divide-gray-300'>
                {
                    repos.map(repo => (
                        <RepoItem key={repo.id} data={repo} />
                    ))
                }
            </ul>
        </div>
    )
}
